### ISSUE TITLE
Suggestion - no need to specify font-weight:bold on h1 and h2s

### ISSUE THREAD

**Issue by jzhu01** [awjdthornton/prj-rev-bwfs-dasmoto#2]
Seen here: https://github.com/awjdthornton/prj-rev-bwfs-dasmoto/blob/master/DasmotosArtsAndCrafts/resources/style.css#L4

Since these are bolded by default, there's no need to state the font-weight.

**Comment by awjdthornton** [comment]
Good to know. I don't think that was pointed out in any of the previous lessons.
